services:
  # Nginx WebServer 서비스
  nowdoboss_frontend_service:
    container_name: nowdoboss-frontend
    build:
      context: ..
      dockerfile: CICD/Nginx/Nginx.Dockerfile
    image: nowdoboss-frontend-img
    restart: always
    environment:
      TZ: ${TZ}
    volumes:
      - ./certbot/conf:/etc/letsencrypt # Certbot이 사용하는 SSL 인증서 경로를 Nginx와 공유합니다.
      - ./certbot/www:/var/www/certbot # Certbot 인증 파일을 저장할 경로를 Nginx와 공유합니다.
      - geoip_data:/usr/share/GeoIP # GeoIP 데이터베이스를 공유합니다.
    ports:
      - '${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}' # Nginx의 HTTP 트래픽을 포트
      - '${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}' # Nginx의 HTTPS 트래픽을 포트
    networks:
      - nowdoboss-net # 애플리케이션 서비스들이 같은 네트워크에 연결되도록 설정합니다.
    command: '/bin/sh -c ''nginx -g "daemon off;"''' # Nginx를 포그라운드에서 실행하여 컨테이너가 종료되지 않도록 합니다.

  # Certbot SSL 관리 서비스
  nowdoboss_certbot_service:
    container_name: nowdoboss-certbot # Certbot 컨테이너 이름을 설정합니다.
    image: certbot/certbot # Let's Encrypt 인증서를 관리하기 위한 Certbot 이미지를 사용합니다.
    restart: always
    environment:
      TZ: ${TZ}
    volumes:
      - ./certbot/conf:/etc/letsencrypt # Certbot이 사용하는 SSL 인증서 경로입니다.
      - ./certbot/www:/var/www/certbot # Certbot의 인증 경로를 설정합니다.
      - /var/run/docker.sock:/var/run/docker.sock # Docker 실행 권한을 추가합니다. (해당 Nginx 도커 컨테이너 SSL 자동 갱신을 위해)
    entrypoint: '/bin/sh -c ''trap exit TERM; while :; do certbot renew --quiet --no-self-upgrade --deploy-hook "docker exec nowdoboss-frontend nginx -s reload"; sleep 12h & wait $${!}; done;''' # Certbot이 인증서를 갱신한 후 Nginx를 자동으로 리로드합니다.
    depends_on:
      - nowdoboss_frontend_service # Nginx가 실행된 후 Certbot이 동작하도록 의존성을 설정합니다.

  # GeoIP 서비스
  geoip_service:
    image: maxmindinc/geoipupdate:latest
    container_name: geoip
    restart: always
    environment:
      GEOIPUPDATE_ACCOUNT_ID: ${GEOIPUPDATE_ACCOUNT_ID}
      GEOIPUPDATE_LICENSE_KEY: ${GEOIPUPDATE_LICENSE_KEY}
      GEOIPUPDATE_EDITION_IDS: ${GEOIPUPDATE_EDITION_IDS}
      GEOIPUPDATE_FREQUENCY: ${GEOIPUPDATE_FREQUENCY}
      TZ: ${TZ}
    volumes:
      - geoip_data:/usr/share/GeoIP # GeoIP 데이터베이스 공유

volumes:
  geoip_data: # GeoIP 데이터 베이스 공유 볼륨

networks:
  nowdoboss-net:
    name: nowdoboss-net
    driver: bridge
