x-spring-boot-environment: &spring_boot_environment
  TZ: Asia/Seoul
  SPRING_BOOT_PORT: ${SPRING_BOOT_PORT}
  SERVER_HTTPS_URL: ${SERVER_HTTPS_URL}
  SERVER_FAST_API_URL: ${SERVER_FAST_API_URL}
  MYSQL_DB_URL: ${MYSQL_DB_URL}
  MYSQL_DB_USERNAME: ${MYSQL_DB_USERNAME}
  MYSQL_DB_PASSWORD: ${MYSQL_DB_PASSWORD}
  MONGO_DB_HOST: ${MONGO_DB_HOST}
  MONGO_DB_DATABASE: ${MONGO_DB_DATABASE}
  MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
  MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
  MONGO_DB_AUTHENTICATION_DATABASE: ${MONGO_DB_AUTHENTICATION_DATABASE}
  JAVA_MAIL_HOST: ${JAVA_MAIL_HOST}
  JAVA_MAIL_USERNAME: ${JAVA_MAIL_USERNAME}
  JAVA_MAIL_PASSWORD: ${JAVA_MAIL_PASSWORD}
  JWT_ACCESS_KEY: ${JWT_ACCESS_KEY}
  JWT_REFRESH_KEY: ${JWT_REFRESH_KEY}
  FIREBASE_BUCKET: ${FIREBASE_BUCKET}
  FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
  OAUTH_KAKAO_CLIENT_ID: ${OAUTH_KAKAO_CLIENT_ID}
  OAUTH_KAKAO_CLIENT_SECRET: ${OAUTH_KAKAO_CLIENT_SECRET}
  OAUTH_NAVER_CLIENT_ID: ${OAUTH_NAVER_CLIENT_ID}
  OAUTH_NAVER_CLIENT_SECRET: ${OAUTH_NAVER_CLIENT_SECRET}
  OAUTH_GOOGLE_CLIENT_ID: ${OAUTH_GOOGLE_CLIENT_ID}
  OAUTH_GOOGLE_CLIENT_SECRET: ${OAUTH_GOOGLE_CLIENT_SECRET}
  JASYPT_ENCRYPTOR_KEY: ${JASYPT_ENCRYPTOR_KEY}


services:
  nowdoboss_springboot_blue_service:
    container_name: nowdoboss-backend-springboot-blue
    build:
      context: .
      dockerfile: SpringBootServer.Dockerfile
    image: nowdoboss-backend-springboot-img:blue
    restart: always
    ports:
      - "${SPRING_BOOT_BLUE_PORT}:${SPRING_BOOT_PORT}"
    environment:
      <<: *spring_boot_environment
    networks:
      - nowdoboss-net

  nowdoboss_springboot_green_service:
    container_name: nowdoboss-backend-springboot-green
    build:
      context: .
      dockerfile: SpringBootServer.Dockerfile
    image: nowdoboss-backend-springboot-img:green
    restart: always
    ports:
      - "${SPRING_BOOT_GREEN_PORT}:${SPRING_BOOT_PORT}"
    environment:
      <<: *spring_boot_environment
    networks:
      - nowdoboss-net

networks:
  nowdoboss-net:
    name: nowdoboss-net
    driver: bridge
