services:
  master1:
    build: 
      context: .
      dockerfile: hd-spark-base.Dockerfile
    container_name: master1
    hostname: master1
    ports:
      - "9870:9870"    # Hadoop NameNode Web UI
      - "8088:8088"    # Hadoop ResourceManager Web UI
      - "19888:19888"  # Hadoop MapReduce JobHistory Server Web UI
      - "7077:7077"    # Spark Master Port
      - "8870:8080"    # Spark Master Web UI
      - "18080:18080"  # Spark History Server
    volumes:
      - shared_keys:/shared_keys
    networks:
      nowdoboss-net:
    command: >
      /bin/bash -c "
      if [ ! -f /setup_completed ]; then
          echo 'Performing initial setup...';
          /usr/local/bin/setup-hadoop.sh &&
          /usr/local/bin/update-hosts.sh &&
          /usr/local/bin/init-ssh-keys.sh &&
          /usr/local/bin/collect-ssh-keys.sh 3 &&
          /usr/local/bin/master/setup-master-hadoop-env.sh &&
          /usr/local/bin/create-hdfs-log-dir.sh &&
          touch /setup_completed;
      else
          echo 'Skipping initial setup, already completed.';
      fi;
      /usr/local/bin/start-master.sh &&
      /usr/local/bin/start-history-server.sh
      "

  worker1:
    build: 
      context: .
      dockerfile: hd-spark-base.Dockerfile
    container_name: worker1
    hostname: worker1
    volumes:
      - shared_keys:/shared_keys
    networks:
      nowdoboss-net:
    command: >
      /bin/bash -c "
      if [ ! -f /setup_completed ]; then
          echo 'Performing initial setup...';
          /usr/local/bin/setup-hadoop.sh &&
          /usr/local/bin/update-hosts.sh &&
          /usr/local/bin/init-ssh-keys.sh &&
          /usr/local/bin/collect-ssh-keys.sh 5 &&
          /usr/local/bin/worker/setup-worker-hadoop-env.sh &&
          touch /setup_completed;
      else
          echo 'Skipping initial setup, already completed.';
      fi;
      /usr/local/bin/start-slave.sh
      "

  worker2:
    build: 
      context: .
      dockerfile: hd-spark-base.Dockerfile
    container_name: worker2
    hostname: worker2
    volumes:
      - shared_keys:/shared_keys
    networks:
      nowdoboss-net:
    command: >
      /bin/bash -c "
      if [ ! -f /setup_completed ]; then
          echo 'Performing initial setup...';
          /usr/local/bin/setup-hadoop.sh &&
          /usr/local/bin/update-hosts.sh &&
          /usr/local/bin/init-ssh-keys.sh &&
          /usr/local/bin/collect-ssh-keys.sh 7 &&
          /usr/local/bin/worker/setup-worker-hadoop-env.sh &&
          touch /setup_completed;
      else
          echo 'Skipping initial setup, already completed.';
      fi;
      /usr/local/bin/start-slave.sh
      "

networks:
  nowdoboss-net:
    name: nowdoboss-net
    driver: bridge

volumes:
  shared_keys:
