x-airflow-environment: &airflow_environment
  AIRFLOW_EXECUTOR: ${AIRFLOW_EXECUTOR}
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
  AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
  AIRFLOW_UID: ${AIRFLOW_UID}
  AIRFLOW_GID: ${AIRFLOW_GID}
  TZ: ${TZ}

services:
  airflow-init:
    image: apache/airflow:latest
    container_name: airflow-init
    restart: always
    environment:
      <<: *airflow_environment
      AIRFLOW_ADMIN_USER: ${AIRFLOW_ADMIN_USER}
      AIRFLOW_ADMIN_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
      AIRFLOW_ADMIN_EMAIL: ${AIRFLOW_ADMIN_EMAIL}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    entrypoint: /bin/bash
    command: >
      -c "
      echo '[airflow-init] Initializing Airflow DB...' &&
      airflow db init &&
      echo '[airflow-init] Creating Admin user...' &&
      airflow users create
        --username ${AIRFLOW_ADMIN_USER}
        --password ${AIRFLOW_ADMIN_PASSWORD}
        --firstname Airflow
        --lastname Admin
        --role Admin
        --email ${AIRFLOW_ADMIN_EMAIL}
      "
    networks:
      - nowdoboss-net

  airflow-scheduler:
    image: apache/airflow:latest
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-init
    environment:
      <<: *airflow_environment
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler
    networks:
      - nowdoboss-net

  airflow-webserver:
    image: apache/airflow:latest
    container_name: airflow-webserver
    restart: always
    depends_on:
      - airflow-scheduler
    environment:
      <<: *airflow_environment
    ports:
      - '${AIRFLOW_WEB_PORT}:8080'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: webserver
    networks:
      - nowdoboss-net

networks:
  nowdoboss-net:
    name: nowdoboss-net
    driver: bridge
