services:
  nowdoboss_backend_fastapi_service:
    container_name: nowdoboss-backend-fastapi
    build: 
      context: .
      dockerfile: FastApiServer.Dockerfile
    image: nowdoboss-backend-fastapi-img 
    restart: always
    ports:
      - "8000:8000"
    networks:
      - nowdoboss-net

networks:
  nowdoboss-net:
    name: nowdoboss-net
    driver: bridge
