server:
  base-url: 1.235.23.72
  https-url: https://1.235.23.72
  fastapi-url: http://13.124.23.220:8000

spring:
  servlet:
    # file 업로드 관련 세팅 (명시적으로 설정 안할 시 Spring boot는 기본적으로 1MB로 설정됨)
    multipart:
      max-file-size: 10MB  # 최대 파일 크기
      max-request-size: 10MB  # 최대 요청 크기

  jpa:
    open-in-view: false
    defer-datasource-initialization: false  # flyway 관련 마이그레이션 이슈 -> false로 변경
    generate-ddl: false
    hibernate:
      ddl-auto: none                # ddl 자동 작성 여부
    properties:
      hibernate:
        format_sql: true             # 하이버네이트가 실행한 SQL을 출력할 때 보기 좋게 정렬
        use_sql_comments: true
        show_sql: true               # 하이버네이트가 실행한 SQL을 출력
        jdbc:
          batch_size: 100              #   insert/update 쿼리를 원하는 개수만큼 모아서 DB에 날릴 수 있는 옵션
        default_batch_fetch_size: 100

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # DB 드라이버
    url: jdbc:mysql://${server.base-url}:3306/nowdoboss?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true       # 데이터베이스 URL
    username: ENC(NYqtFSaM0KYco+Y8zivxH10AFbmGUc5b)             # 데이터베이스 계정명
    password: ENC(1+qm22EMFffu+LHZSW+HOP3Ikh9gK4vY)             # 데이터베이스 계정 비밀번호

  # NoSQL setting
  data:
    # Redis setting
    redis:
      host: redis # Redis 도커 컨테이너의 이름을 사용하여 접근 (같은 네트워크로 묶여야함)
      port: 6379

    # MongoDB setting
    mongodb:
      host: ${server.base-url}
      port: 27017
      database: 8llow8llowme
      username: 8llow8llowme
      password: 8llow8llowme
      authentication-database: admin

  # Java Mail Sender setting (Google Mail)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(+5jsIIJ6sQhfHib/WLZpOFVfaUB3j8nSAPvugM5tbA0=)
    password: ENC(fXL++uSC79xcGgMraAlzsef+TJaoxLIsEJlEtsWt/gU=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Kafka setting
  kafka:
    bootstrap-servers: kafka-1:29092, kafka-2:29093, kafka-3:29094 # 도커에서 설정한 내부 서비스명으로 접근 (내부 네트워크 이용)
    consumer:
      group-id: NowDoBossGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  # flyway setting
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false

  mvc:
    async:
      request-timeout: 3000000

# log 관리
logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      org.hibernate.SQLQuery: debug

# jwt setting
jwt:
  accessKey: ENC(sVO5iJmm3kQWp+iZwdwYOHW0o4mkgUQTv5AcpmBJ3tCSuTe59lryqbOj57lG9bv133Sr5fR9RRbY0I/mtphYQ2In6Key9xPsxLDs7izg+d5k21KswSys5PZ8h1T7Aq3dNujkA9DBkOGi3JinArAlsJNVcn2CoSyiVAd0Ke4D1SVwjnzMNMjPCkDHf9A9oTP6k2L+z/CAPd9338OYqS2SnQ==)
  refreshKey: ENC(qvalG2VA7BkYezISPg6ik5iNLpB4062CoNvw3gzFcWHNwciYfCkRO9wklS1r9zKAJeTsi9f5ewtz4m/o+u2CjUAqrZIWJ+WTuFFV1G9o3hR+61vG7dLa+81lX7OljJD6jq/zrWBUjDUNwBPcZVkuvVKkXs03+L3/EYr0WzykXKkgpvt9q0LkUtskHYJNnsvBxNxivjpiUuxOwbfD0DRSAA==)
  accessExpiration: PT420M  # 420분 (PT420M)
  refreshExpiration: PT10080M  # 10080분 (7일) (PT10080M)

# firebase setting
app:
  firebase-configuration-file: classpath:serviceAccountKey.json
  firebase-bucket: ENC(QyKD4uz1kofezMLc1GD9dpLblXKaIfU+nhv1KP3JinQ=)
  firebase-project-id: nowdoboss

# OAUTH2.0 Setting
oauth:
  kakao:
    client-id: ENC(g/Vx8WTW7h5I2QZf+9dtLW/7kjmFO8ShBdsZTCs5X0737/ionud6CrjbnHWW/yx5)   # REST API 키
    client-secret: ENC(asP3isod96DLoonCJyrARCQRjHmExfVqQQoksnX460rHQ5w8rdzRMYqUGZyswq9E) # 보안 -> Client Secret 키
    redirect-uri: ${server.https-url}/member/loading/kakao
    scope:
      - profile_nickname
      - profile_image
      - account_email
#      - name

  naver:
    client-id: ENC(8NHWe8Pgm5HfHuGZIqIsoJoOZHq/FEp1b2s9nrWwyAw=)
    client-secret: ENC(OWV9NuO9XtzrcStSseRpG0aLL7wUg06y)
    redirect_uri: ${server.https-url}/member/loading/naver
    scope:
      - nickname
      - name
      - email
      - profile_image

  google:
    client_id: ENC(h60iOgCEaWm1FoBAE2egg1lFRiY2KDxtJk8hWsM3o2Pqc82z9xjFBpU27igPlAFZNvsuJPAiTihg9eixh8hXVje40XNOHBirDhNoqeCPM2VKGpeQtFAEZg==)
    client_secret: ENC(WMCJejXDWzF/LMCkmM6nAwF6T6gnF1U/wPsSLLnWwr27VyggAbLclQmiwUM1YgWU)
    redirect_uri: ${server.https-url}/member/loading/google
    scope:
      - profile
      - email
