server:
  base-url: localhost
  fast-api-url: http://localhost:8001

spring:
  servlet:
    # file 업로드 관련 세팅 (명시적으로 설정 안할 시 Spring boot는 기본적으로 1MB로 설정됨)
    multipart:
      max-file-size: 10MB  # 최대 파일 크기
      max-request-size: 10MB  # 최대 요청 크기

  jpa:
    open-in-view: false
    defer-datasource-initialization: false
    generate-ddl: false
    hibernate:
      ddl-auto: none                # ddl 자동 작성 여부
    properties:
      hibernate:
        format_sql: true             # 하이버네이트가 실행한 SQL을 출력할 때 보기 좋게 정렬
        use_sql_comments: true
        show_sql: true               # 하이버네이트가 실행한 SQL을 출력
        jdbc:
          batch_size: 100              #   insert/update 쿼리를 원하는 개수만큼 모아서 DB에 날릴 수 있는 옵션
        default_batch_fetch_size: 100

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # DB 드라이버
    url: jdbc:mysql://${server.base-url}:3306/nowdoboss?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true       # 데이터베이스 URL
    username: ENC(akJyoQsbvBpIR8Hr/6gHrMKbTXs+Ob6s)                     # 데이터베이스 계정명
    password: ENC(qMqsUHHJbnVXen27G8/40fAjKwR5tYBuTJaB4HYd1vw=)         # 데이터베이스 계정 비밀번호

  # data_테이블명.sql 관련 실행 setting (더미데이터)
  #  sql:
  #    init:
  #      mode: always
  #      data-locations:
  #        - 'classpath:/db/dummy/FOREIGN_KEY_CHECKS_0.sql'
  #        - 'classpath:/db/dummy/db_dump.sql'
  #        - 'classpath:/db/dummy/db_dump1.sql'
  #        - 'classpath:/db/dummy/db_dump2.sql'
  #        - 'classpath:/db/dummy/FOREIGN_KEY_CHECKS_1.sql'

  # NoSQL setting
  data:
    # Redis setting
    redis:
      host: ${server.base-url}
      port: 6379

    # MongoDB setting
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27017
      database: ENC(TsihpAwI+2KlpkV7OZXu75xbdsM0wcJA)
      username: ENC(DkrVZoXLsSjuunsNJbFyiGGRz2fzhBNq)
      password: ENC(xmrow2QycvAiBGA+53sxhBL+W3HbZrFzlBrRnyiycKA=)
      authentication-database: ENC(kGONsEZYcgxAFauoUqW1Lw==)


  # Java Mail Sender setting (Google Mail)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(+5jsIIJ6sQhfHib/WLZpOFVfaUB3j8nSAPvugM5tbA0=)
    password: ENC(fXL++uSC79xcGgMraAlzsef+TJaoxLIsEJlEtsWt/gU=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Kafka setting
  kafka:
    bootstrap-servers: ${server.base-url}:9092, ${server.base-url}:9093, ${server.base-url}:9094
    consumer:
      group-id: NowDoBossGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # flyway setting
  flyway:
    enabled: false  # Flyway 비활성화

  mvc:
    async:
      request-timeout: 3000000

# log 관리
logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      org.hibernate.SQLQuery: debug

# jwt setting
jwt:
  accessKey: ENC(sVO5iJmm3kQWp+iZwdwYOHW0o4mkgUQTv5AcpmBJ3tCSuTe59lryqbOj57lG9bv133Sr5fR9RRbY0I/mtphYQ2In6Key9xPsxLDs7izg+d5k21KswSys5PZ8h1T7Aq3dNujkA9DBkOGi3JinArAlsJNVcn2CoSyiVAd0Ke4D1SVwjnzMNMjPCkDHf9A9oTP6k2L+z/CAPd9338OYqS2SnQ==)
  refreshKey: ENC(qvalG2VA7BkYezISPg6ik5iNLpB4062CoNvw3gzFcWHNwciYfCkRO9wklS1r9zKAJeTsi9f5ewtz4m/o+u2CjUAqrZIWJ+WTuFFV1G9o3hR+61vG7dLa+81lX7OljJD6jq/zrWBUjDUNwBPcZVkuvVKkXs03+L3/EYr0WzykXKkgpvt9q0LkUtskHYJNnsvBxNxivjpiUuxOwbfD0DRSAA==)
  accessExpiration: PT420M  # 420분 (PT420M)
  refreshExpiration: PT10080M  # 10080분 (7일) (PT10080M)

# firebase setting
app:
  firebase-configuration-file: classpath:backend-env/serviceAccountKey.json
  firebase-bucket: ENC(QyKD4uz1kofezMLc1GD9dpLblXKaIfU+nhv1KP3JinQ=)
  firebase-project-id: ENC(XtdIGmHURYv0IWAPbw4PiggbwHuJYiIP)

# OAUTH2.0 Setting
oauth:
  kakao:
    client-id: ENC(g/Vx8WTW7h5I2QZf+9dtLW/7kjmFO8ShBdsZTCs5X0737/ionud6CrjbnHWW/yx5)   # REST API 키
    client-secret: ENC(asP3isod96DLoonCJyrARCQRjHmExfVqQQoksnX460rHQ5w8rdzRMYqUGZyswq9E) # 보안 -> Client Secret 키
    redirect-uri: http://${server.base-url}:5173/member/loading/kakao
    scope:
      - profile_nickname
      - profile_image
      - account_email
      - name

  naver:
    client-id: ENC(8NHWe8Pgm5HfHuGZIqIsoJoOZHq/FEp1b2s9nrWwyAw=)
    client-secret: ENC(OWV9NuO9XtzrcStSseRpG0aLL7wUg06y)
    redirect_uri: http://${server.base-url}:5173/member/loading/naver
    scope:
      - nickname
      - name
      - email
      - profile_image

  google:
    client_id: ENC(h60iOgCEaWm1FoBAE2egg1lFRiY2KDxtJk8hWsM3o2Pqc82z9xjFBpU27igPlAFZNvsuJPAiTihg9eixh8hXVje40XNOHBirDhNoqeCPM2VKGpeQtFAEZg==)
    client_secret: ENC(WMCJejXDWzF/LMCkmM6nAwF6T6gnF1U/wPsSLLnWwr27VyggAbLclQmiwUM1YgWU)
    redirect_uri: http://${server.base-url}:5173/member/loading/google
    scope:
      - profile
      - email
